---
name: Grafana Loki
version: dev
slug: loki
description: "Loki: like Prometheus, but for logs."
url: "https://github.com/mcinnes01/ha-addon-grafana-loki/blob/main/loki"
watchdog: http://[HOST]:3100/ready
apparmor: false
ports:
  3100/tcp: null
  9096/tcp: null
ports_description:
  3100/tcp: Loki
  9096/tcp: gRPC
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
homeassistant_api: true
image: "ghcr.io/mcinnes01/{arch}-ha-addon-grafana-loki"
