---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
    assignees:
      - cedricziel
  - package-ecosystem: "docker"
    directory: "/loki"
    schedule:
      interval: weekly
      time: "06:00"
    assignees:
      - cedricziel
